 		update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [IdEstado] =null WHERE [IdEstado] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Estado] =null WHERE [Estado] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Clave_UMAFOR] =null WHERE [Clave_UMAFOR] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Familia_APG] =null WHERE [Familia_APG] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Genero_APG] =null WHERE [Genero_APG] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Especie_APG] =null WHERE [Especie_APG] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Cat_Infra_APG] =null WHERE [Cat_Infra_APG] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Infra_APG] =null WHERE [Infra_APG] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Nombre_APG] =null WHERE [Nombre_APG] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Clave_ecuacion] =null WHERE [Clave_ecuacion] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Aplicacion] =null WHERE [Aplicacion] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Num_Observaciones] =null WHERE [Num_Observaciones] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [R2] =null WHERE [R2] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [F] =null WHERE [F] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [REMC] =null WHERE [REMC] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Fuente] =null WHERE [Fuente] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Eco_N1] =null WHERE [Eco_N1] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Eco_N2] =null WHERE [Eco_N2] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Eco_N3] =null WHERE [Eco_N3] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Eco_N4] =null WHERE [Eco_N4] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Ecuacion] =null WHERE [Ecuacion] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Rango_Diam] =null WHERE [Rango_Diam] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Rango_Alt] =null WHERE [Rango_Alt] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C1] =null WHERE [C1] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C2] =null WHERE [C2] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C3] =null WHERE [C3] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C4] =null WHERE [C4] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C5] =null WHERE [C5] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C_cm] =null WHERE [C_cm] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [V1] =null WHERE [V1] like 'null%'
      update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [V2] =null WHERE [V2] like 'null%'

update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [IdEstado] = ltrim(rtrim([IdEstado]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Estado] =  ltrim(rtrim([Estado]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Clave_UMAFOR] =  ltrim(rtrim([Clave_UMAFOR]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Familia_APG] =  ltrim(rtrim([Familia_APG]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Genero_APG] =  ltrim(rtrim([Genero_APG]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Especie_APG] =  ltrim(rtrim([Especie_APG]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Cat_Infra_APG] =  ltrim(rtrim([Cat_Infra_APG]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Infra_APG] =  ltrim(rtrim([Infra_APG]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Nombre_APG] =  ltrim(rtrim([Nombre_APG]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Clave_ecuacion] =  ltrim(rtrim([Clave_ecuacion]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Aplicacion] =  ltrim(rtrim([Aplicacion]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Num_Observaciones] =  ltrim(rtrim([Num_Observaciones]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [R2] =  ltrim(rtrim([R2]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [F] =  ltrim(rtrim([F]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [REMC] =  ltrim(rtrim([REMC]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Fuente] =  ltrim(rtrim([Fuente]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Eco_N1] =  ltrim(rtrim([Eco_N1]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Eco_N2] =  ltrim(rtrim([Eco_N2]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Eco_N3] =  ltrim(rtrim([Eco_N3]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Eco_N4] =  ltrim(rtrim([Eco_N4]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Ecuacion] =  ltrim(rtrim([Ecuacion]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Rango_Diam] =  ltrim(rtrim([Rango_Diam]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [Rango_Alt] =  ltrim(rtrim([Rango_Alt]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C1] =  ltrim(rtrim([C1]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C2] =  ltrim(rtrim([C2]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C3] =  ltrim(rtrim([C3]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C4] =  ltrim(rtrim([C4]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C5] =  ltrim(rtrim([C5]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [C_cm] =  ltrim(rtrim([C_cm]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [V1] =  ltrim(rtrim([V1]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [V2] =  ltrim(rtrim([V2]))
update [ArbolDesiciones].dbo.Ecuaciones_VRTA_2 set [IdEstado] =  ltrim(rtrim([IdEstado]))
